import Head from "next/head";
import { WalletSection } from "../components";
import { useTheme } from "../contexts/theme";
import { MoonIcon, SunIcon } from "@heroicons/react/24/outline";

import { DAO } from "../components/dao";

export default function Home() {
  const chainName = process.env.NEXT_PUBLIC_CHAIN ?? "localnet";
  const { theme, toggleTheme } = useTheme();

  return (
    <div className="max-w-5xl py-10 mx-6 lg:mx-auto">
      <Head>
        <title>DAO</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row justify-end mb-4"></div>
      <div className="text-center">
        <h1 className="mb-3 text-3xl font-bold sm:text-4xl md:text-5xl">DAO</h1>
      </div>
      <WalletSection chainName={chainName} />
      <DAO address="juno17p9rzwnnfxcjp32un9ug7yhhzgtkhvl9jfksztgw5uh69wac2pgszu8fr9" />
    </div>
  );
}
